"""Async pipeline: fetch students → papers → arXiv abstracts → LLM analysis → save."""
from __future__ import annotations

import asyncio
import logging
from datetime import date, timedelta
from pathlib import Path

from app.schemas.intel.paper_transfer import (
    PaperMeta,
    PaperTransferResults,
    PipelineProgress,
    PipelineRunState,
    StudentContact,
    StudentMeta,
    TransformationCard,
)
from app.services.intel.paper_transfer.external_api import (
    fetch_all_students,
    fetch_arxiv_abstract,
    fetch_student_papers,
)
from app.services.intel.paper_transfer.llm import enrich_paper
from app.services.intel.paper_transfer.rules import classify_paper_by_rules

logger = logging.getLogger(__name__)

_RESULTS_DIR = Path("data/processed/paper_transfer")
_STATE_FILE = _RESULTS_DIR / "run_state.json"
_RESULTS_FILE = _RESULTS_DIR / "results.json"
# Fallback: pre-committed results shipped with the repo (skills/)
_FALLBACK_RESULTS_FILE = Path("skills/paper_transfer_results.json")

# In-process guard: only one pipeline run at a time
_running = False


def _save_state(state: PipelineRunState) -> None:
    _RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    tmp = _STATE_FILE.with_suffix(".tmp")
    tmp.write_text(state.model_dump_json(indent=2), encoding="utf-8")
    tmp.replace(_STATE_FILE)


def load_state() -> PipelineRunState:
    if not _STATE_FILE.exists():
        return PipelineRunState(status="idle")
    try:
        return PipelineRunState.model_validate_json(_STATE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return PipelineRunState(status="idle")


def load_results() -> PaperTransferResults | None:
    # Primary: data/processed/paper_transfer/results.json (generated by pipeline)
    # Fallback: skills/paper_transfer_results.json (pre-committed, used on fresh deploy)
    for results_file in (_RESULTS_FILE, _FALLBACK_RESULTS_FILE):
        if not results_file.exists():
            continue
        try:
            return PaperTransferResults.model_validate_json(
                results_file.read_text(encoding="utf-8")
            )
        except Exception:
            continue
    return None


def is_running() -> bool:
    return _running


async def run_pipeline(
    date_from: str | None,
    school_filter: str | None,
    max_papers: int,
    batch_size: int,
) -> None:
    """Full pipeline: fetch → enrich → classify (batched serial) → save.

    Papers are split into batches of `batch_size` and processed one batch at a time
    to keep memory bounded and allow partial-result recovery. Each batch is saved to
    batch_NNN.json; a merged results.json is written when all batches complete.

    Intended to be run as an asyncio background task via asyncio.create_task().
    """
    global _running
    _running = True

    from datetime import datetime, timezone

    def now_iso() -> str:
        return datetime.now(timezone.utc).isoformat()

    if not date_from:
        date_from = (date.today() - timedelta(days=180)).isoformat()

    state = PipelineRunState(
        status="running",
        started_at=now_iso(),
        date_from=date_from,
        school_filter=school_filter,
        max_papers=max_papers,
        batch_size=batch_size,
        progress=PipelineProgress(),
    )
    _save_state(state)

    try:
        # ── Stage 1: Fetch students ──────────────────────────────────────────
        students = await fetch_all_students(school_filter)
        state.progress.students_fetched = len(students)
        _save_state(state)
        logger.info("Stage 1 done: %d students fetched", len(students))

        # ── Stage 2: Fetch papers for every student (concurrent, max 10) ────
        fetch_semaphore = asyncio.Semaphore(10)

        async def _fetch_papers(student: dict) -> list[tuple[dict, dict]]:
            async with fetch_semaphore:
                papers = await fetch_student_papers(student["student_id"], date_from)
            return [(paper, student) for paper in papers]

        results_per_student = await asyncio.gather(
            *[_fetch_papers(s) for s in students]
        )
        all_pairs: list[tuple[dict, dict]] = [
            pair for pairs in results_per_student for pair in pairs
        ]

        state.progress.papers_fetched = len(all_pairs)
        _save_state(state)
        logger.info("Stage 2 done: %d paper-student pairs fetched", len(all_pairs))

        # Apply max_papers cap: keep newest papers first
        if len(all_pairs) > max_papers:
            all_pairs.sort(
                key=lambda x: x[0].get("publication_date") or "", reverse=True
            )
            all_pairs = all_pairs[:max_papers]
            logger.info("Capped to %d pairs per max_papers limit", max_papers)

        # ── Stage 3: Fetch arXiv abstracts (concurrent, max 10 in flight) ───
        abstract_semaphore = asyncio.Semaphore(10)

        async def _fetch_abstract(pair: tuple[dict, dict]) -> tuple[dict, dict]:
            paper, student = pair
            if paper.get("arxiv_id") and not paper.get("abstract"):
                async with abstract_semaphore:
                    abstract = await fetch_arxiv_abstract(paper["arxiv_id"])
                    paper = {**paper, "abstract": abstract}
            return paper, student

        enriched_pairs = list(
            await asyncio.gather(*[_fetch_abstract(p) for p in all_pairs])
        )
        state.progress.abstracts_fetched = sum(
            1 for p, _ in enriched_pairs if p.get("abstract")
        )
        _save_state(state)
        logger.info(
            "Stage 3 done: %d abstracts fetched", state.progress.abstracts_fetched
        )

        # ── Stage 4: LLM classification — batched serial ─────────────────────
        # Papers are split into batches of `batch_size`. Each batch is processed
        # concurrently within itself (semaphore=5), but batches run one at a time
        # to keep the number of in-flight LLM calls bounded and allow per-batch saves.

        def _build_card(
            paper: dict, student: dict, llm_result: dict, rule_result: dict
        ) -> TransformationCard:
            raw_contact = student.get("contact") or {}
            return TransformationCard(
                paper=PaperMeta(
                    paper_id=paper.get("paper_id", ""),
                    title=paper.get("title", ""),
                    url=paper.get("url"),
                    publication_date=paper.get("publication_date"),
                    venue=paper.get("venue"),
                    doi=paper.get("doi"),
                    arxiv_id=paper.get("arxiv_id"),
                    student_name_list=paper.get("student_name_list") or [],
                ),
                student=StudentMeta(
                    student_id=student.get("student_id", ""),
                    name=student.get("name", ""),
                    name_cn=student.get("name_cn", ""),
                    name_en=student.get("name_en", ""),
                    school=student.get("school", ""),
                    school_cn=student.get("school_cn", ""),
                    contact=StudentContact(
                        email=raw_contact.get("email"),
                        phone=raw_contact.get("phone"),
                        wechat=raw_contact.get("wechat"),
                    ),
                ),
                grade=llm_result["grade"],
                grade_reason=llm_result["grade_reason"],
                content_type=llm_result.get("content_type") or rule_result["content_type"],
                commercialization_tier=(
                    llm_result.get("commercialization_tier")
                    or rule_result["commercialization_tier"]
                ),
                matched_signals=rule_result["matched_signals"],
                tech_summary=llm_result["tech_summary"],
                transformation_directions=llm_result["transformation_directions"],
                maturity_level=llm_result["maturity_level"],
                negotiation_angle=llm_result["negotiation_angle"],
                recommendation_reason=llm_result["recommendation_reason"],
            )

        n_batches = max(1, (len(enriched_pairs) + batch_size - 1) // batch_size)
        state.progress.total_batches = n_batches
        _save_state(state)
        logger.info(
            "Stage 4 start: %d papers → %d batches of ~%d",
            len(enriched_pairs), n_batches, batch_size,
        )

        llm_semaphore = asyncio.Semaphore(5)
        all_cards: list[TransformationCard] = []

        # Clean up any stale batch files from a previous run
        for old in _RESULTS_DIR.glob("batch_*.json"):
            old.unlink(missing_ok=True)

        for batch_idx in range(n_batches):
            batch_start = batch_idx * batch_size
            batch_pairs = enriched_pairs[batch_start: batch_start + batch_size]

            state.progress.current_batch = batch_idx + 1
            _save_state(state)
            logger.info(
                "Batch %d/%d: analyzing %d papers",
                batch_idx + 1, n_batches, len(batch_pairs),
            )

            async def _analyze(paper: dict, student: dict) -> TransformationCard:
                rule_result = classify_paper_by_rules(
                    paper.get("title", ""), paper.get("abstract")
                )
                async with llm_semaphore:
                    llm_result = await enrich_paper(
                        title=paper.get("title", ""),
                        abstract=paper.get("abstract"),
                        venue=paper.get("venue"),
                        publication_date=paper.get("publication_date"),
                    )
                return _build_card(paper, student, llm_result, rule_result)

            batch_cards: list[TransformationCard] = list(
                await asyncio.gather(*[_analyze(p, s) for p, s in batch_pairs])
            )
            all_cards.extend(batch_cards)

            # Save this batch's results
            batch_file = _RESULTS_DIR / f"batch_{batch_idx + 1:03d}.json"
            _RESULTS_DIR.mkdir(parents=True, exist_ok=True)
            batch_grade_counts: dict[str, int] = {"A": 0, "B": 0, "C": 0}
            for c in batch_cards:
                batch_grade_counts[c.grade] = batch_grade_counts.get(c.grade, 0) + 1
            batch_result = PaperTransferResults(
                generated_at=now_iso(),
                total_students_processed=len(students),
                total_papers_fetched=state.progress.papers_fetched,
                total_papers_analyzed=len(batch_cards),
                grade_counts=batch_grade_counts,
                batch_count=1,
                items=batch_cards,
            )
            tmp = batch_file.with_suffix(".tmp")
            tmp.write_text(batch_result.model_dump_json(indent=2), encoding="utf-8")
            tmp.replace(batch_file)

            state.progress.papers_analyzed = len(all_cards)
            _save_state(state)
            logger.info(
                "Batch %d/%d done: A=%d B=%d C=%d (total analyzed: %d)",
                batch_idx + 1, n_batches,
                batch_grade_counts["A"], batch_grade_counts["B"], batch_grade_counts["C"],
                len(all_cards),
            )

        logger.info("Stage 4 done: all %d batches complete", n_batches)

        # ── Stage 5: Merge all batches and save results.json ─────────────────
        grade_counts: dict[str, int] = {"A": 0, "B": 0, "C": 0}
        for card in all_cards:
            grade_counts[card.grade] = grade_counts.get(card.grade, 0) + 1

        # Sort: A → B → C, then by commercialization tier asc within grade
        _grade_order = {"A": 0, "B": 1, "C": 2}
        cards_sorted = sorted(
            all_cards,
            key=lambda c: (_grade_order.get(c.grade, 3), c.commercialization_tier),
        )

        results = PaperTransferResults(
            generated_at=now_iso(),
            total_students_processed=len(students),
            total_papers_fetched=state.progress.papers_fetched,
            total_papers_analyzed=len(all_cards),
            grade_counts=grade_counts,
            batch_count=n_batches,
            items=cards_sorted,
        )

        _RESULTS_DIR.mkdir(parents=True, exist_ok=True)
        tmp = _RESULTS_FILE.with_suffix(".tmp")
        tmp.write_text(results.model_dump_json(indent=2), encoding="utf-8")
        tmp.replace(_RESULTS_FILE)

        state.status = "completed"
        state.completed_at = now_iso()
        _save_state(state)
        logger.info(
            "Pipeline completed: %d batches, A=%d B=%d C=%d",
            n_batches, grade_counts["A"], grade_counts["B"], grade_counts["C"],
        )

    except Exception as e:
        logger.exception("Pipeline failed: %s", e)
        state.status = "failed"
        state.error = str(e)
        _save_state(state)
    finally:
        _running = False
